Repository contactlab/contactlab-ui-components, pull requests merged in 2018-04, with the labels that each got.

#203 updated Polymer to v3.0.0-pre.12
  demo/demo-element.js
  package.json
  src/accordion/index.js
  src/alert/index.js
  src/autocomplete/index.js
  src/button-group/index.js
  src/button/index.js
  src/calendar/index.js
  src/card/index.js
  src/checkbox/index.js
  src/curtain/index.js
  src/dropdown/index.js
  src/feature/index.js
  src/file/index.js
  src/input/index.js
  src/label-badge/index.js
  src/modal/index.js
  src/multiple/index.js
  src/note/index.js
  src/pagination/index.js
  src/progress-bar/index.js
  src/radio/index.js
  src/range/index.js
  src/spinner/index.js
  src/tabs/index.js
  src/tags/index.js
  src/tooltip/index.js
  yarn.lock
Labels: Bug ⓧ, Polymer 3 ♔

#204 Version 2.0.9 + deprecation
  README.md
  package-lock.json
  package.json
Labels: Critical ⚠️, Polymer 3 ♔

#205 Release 1.4.16
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: Critical ⚠️
